memories/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'memories'
urlpatterns = [
    path('', views.index, name='home'),
    path('memorys/', views.MemoryView.as_view(), name='memorys'),
    path('memory/<int:memory_id>/', views.MemoryDetailView.as_view(), name='memory'),
    path('memory/new_memory/', views.NewMemoryView.as_view(), name='new_memory'),
    path('memory/edit_memory/<int:memory_id>/', views.EditMemoryView.as_view(), name='edit_memory'),
    path('memory/edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('memory/edit_interest/', views.EditInterstedView.as_view(), name='edit_interest'),
]

notebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memories.urls')),
    path('users/', include('users.urls'))

]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
	path('login/',views.loginview, name='login'),
	path('logout/',views.logoutview, name='logout'),
	path('register/', views.register, name='register')
]

memories/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Memory(models.Model):
    STATUS_TYPE = (('pu', 'عمومی'), ('pr', 'خصوصی'),)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.TextField()
    place = models.CharField(max_length=15)
    history = models.DateTimeField()
    ftravel = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=2, choices=STATUS_TYPE, default='pr')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-create',)


class Profile(models.Model):
    job = models.CharField(max_length=20, blank=True)
    place = models.CharField(max_length=20, blank=True)
    birthday = models.DateField(blank=True)
    avatar = models.ImageField(upload_to='images/%User/%Y/%m/%d/')
    profile = models.OneToOneField(User, on_delete=models.CASCADE)


class Tags(models.Model):
    tag = models.CharField(max_length=10)

    def __str__(self):
        return self.tag


class Interests(models.Model):
    interest = models.OneToOneField(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tags, blank=True)

    def __str__(self):
        return self.interest.username


class Comment(models.Model):
    memory = models.ForeignKey(Memory, on_delete=models.CASCADE, blank=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    comment = models.TextField(max_length=150)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.writer.username

memories/forms.py
from django import forms
from .models import Memory, Profile, Interests, Comment


class MemoryForm(forms.ModelForm):
    class Meta:
        model = Memory
        fields = ('title', 'text', 'place',
                  'history', 'ftravel', 'image',
                  'type')
        labels = {'title': 'موضوع:', 'text': 'متن:', 'place': 'مکان:',
                  'history': 'تاریخ:', 'ftravel': 'هم خاطره ها:', 'image': 'عکس خاطره:',
                  'type': 'نوع خاطره:'}


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('job', 'place', 'birthday', 'avatar')
        labels = {'job': 'شغل:', 'place': 'محل زندگی:', 'birthday': 'تاریخ تولد:', 'avatar': 'عکس:'}

class InterestsForm(forms.ModelForm):
    class Meta:
        model = Interests
        fields = ('tag',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

memories/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Memory, Profile, Interests, Comment
from .forms import MemoryForm, ProfileForm, InterestsForm, CommentForm
import random


# Create your views here.
def index(request):
    memories = Memory.objects.filter(type='pu')

    return render(request, 'notebook/index.html',
                      {'memories': memories})


class MemoryView(ListView):
    def get(self, request):
        try:
            memories = Memory.objects.filter(writer=request.user)
            return render(request, 'notebook/memories.html',
                          {'memories': memories})
        except TypeError:
            return redirect('memories:home')


class MemoryDetailView(DetailView):
    def get(self, request, memory_id):
        memory = Memory.objects.get(id=memory_id)
        memories = Memory.objects.all()
        try:
            comments = Comment.objects.filter(memory=memory_id)
            form = CommentForm()
        except Comment.DoesNotExist:
            form = CommentForm()
        return render(request, 'notebook/memory.html',
                      {'memories': memories, 'memory': memory, 'form': form, 'comments': comments})

    def post(self, request, memory_id):
        form = CommentForm(data=request.POST)
        print("1")
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.memory = Memory.objects.get(id=memory_id)
            new_comment.writer = request.user
            new_comment.save()
            return redirect('memories:memory', memory_id)


class NewMemoryView(ListView):
    def get(self, request):
        form = MemoryForm()
        memories = Memory.objects.all()
        return render(request, 'notebook/new_memory.html',
                      {'form': form, 'memories': memories})

    def post(self, request):
        form = MemoryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_memory = form.save(commit=False)
            new_memory.writer = request.user
            new_memory.save()
        return redirect('memories:memorys')


class EditMemoryView(ListView):
    def get(self, request, memory_id):
        memory = Memory.objects.get(id=memory_id)
        form = MemoryForm(instance=memory)
        return render(request, 'notebook/edit_memory.html', {'memory': memory, 'form': form})

    def post(self, request, memory_id):
        print(request.POST)
        memory = Memory.objects.get(id=memory_id)
        form = MemoryForm(instance=memory, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('memories:memorys')


class EditProfileView(ListView):
    def get(self, request):
        try:
            profile = Profile.objects.get(profile=request.user)
            form = ProfileForm(instance=profile)
        except TypeError:
            return redirect("users:login")
        except Profile.DoesNotExist:
            form = ProfileForm()

        return render(request, 'notebook/edit_profile.html', {'form': form})

    def post(self, request):
        try:
            profile = Profile.objects.get(profile=request.user)
            form = ProfileForm(instance=profile, data=request.POST, files=request.FILES)
        except Profile.DoesNotExist:
            form = ProfileForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            new_profile = form.save(commit=False)
            new_profile.profile = request.user
            new_profile.save()
            return redirect('memories:home')


class EditInterstedView(ListView):
    def get(self, request):
        try:
            interest = Interests.objects.get(interest=request.user)
            form = InterestsForm(instance=interest)
        except Interests.DoesNotExist:
            form = InterestsForm()
        return render(request, 'notebook/edit_interest.html', {'form': form})

    def post(self, request):
        try:
            interest = Interests.objects.get(interest=request.user)
            form = InterestsForm(instance=interest, data=request.POST)
        except Interests.DoesNotExist:
            interest = Interests.objects.create(interest=request.user)
            form = InterestsForm(intance=interest, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('memories:home')

memories/templates/notebook/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
<head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        html, body, h1, h2, h3, h4, h5, h6 {
            font-family: Mj_Parand
        }
    </style>
</head>
<body class="w3-theme-l5">
{% include 'notebook/header.html' %}
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
    <!-- The Grid -->
    <div class="w3-row">
        {% include 'notebook/lefter.html' %}
        <div class="w3-col m7">
            <div class="w3-row-padding">
                <div class="w3-col m12">
                    <div class="w3-card w3-round w3-white">
                        <div class="w3-container w3-padding"> {% block content %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'notebook/righter.html' %}
    </div>   <!-- End Grid -->
</div>  <!-- End Page Container -->
{% include 'notebook/footer.html' %}
</body>
</html>

memories/templates/notebook/edit_interest.html
{% extends 'notebook/base.html' %}
{% block content %}
<form enctype="multipart/form-data" action="{% url 'memories:edit_interest'%}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  ثبت ویرایش</button>
</form>
{% endblock content %}

memories/templates/notebook/edit_memory.html
{% extends 'notebook/base.html' %}
{% block content %}
{% if request.user.is_authenticated and request.user == memory.writer %}
<form enctype="multipart/form-data" action="{% url 'memories:edit_memory' memory.id%}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">ثبت ویرایش</button>

</form>
{% else %}
<h2>دسترسی شما به این صفحه مجاز نیس</h2>
<h6> برای ورود <a href="{% url 'users:login' %}">اینحا</a> کلیک کنید</h6>
<h6> برای ثبت نام <a href="{% url 'users:register' %}">اینحا</a> کلیک کنید</h6>
{% endif %}
{% endblock content %}

memories/templates/notebook/edit_profile.html
{% extends 'notebook/base.html' %}
{% block content %}
<form enctype="multipart/form-data" action="{% url 'memories:edit_profile'%}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  ثبت ویرایش</button>
</form>
{% endblock content %}

memories/templates/notebook/footer.html
{% load static %}
<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
</footer>



<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else {
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

memories/templates/notebook/header.html
{% load static %}
<!-- Navbar -->
<div class="w3-top">
    <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
        <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2"
           href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
        <a href="{% url 'memories:memorys' %}" class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i
                class="fa fa-home w3-margin-right"></i>دفترچه خاطرات</a>
        <a href="{% url 'memories:home' %}"
           class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="همه خاطرات"><i
                class="fa fa-globe"></i></a>
        <a href="{% url 'memories:edit_profile'%}"
           class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="ویرایش پروفایل"><i
                class="fa fa-user"></i></a>
        <a href="{% url 'memories:new_memory'%}"
           class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white"
           title="ثبت خاطره ی جدید"><i class="fa fa-envelope"></i></a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'memories:memorys' %}"
           class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="My Account">
            <img src="/media/{{profile1.avatar}}" class="w3-circle" style="height:23px;width:23px" alt="Avatar">
        </a>

        <b class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white">{{request.user.first_name}}عزیر
            به صفحه ی خاطرات خوش آمدی </b>
        <a href="{% url 'users:logout' %}"
           class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white"
           title="My Account">خروج</a>
        {% else %}
        <a href="{% url 'users:login' %}"
           class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white"
           title="My Account">ورود</a>
        <a href="{% url 'users:register' %}"
           class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white"
           title="My Account">ثبتنام</a>
        {% endif %}
    </div>
</div>

<!-- Navbar on small screens -->
{% if request.user.is_authenticated %}
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">

    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
    <b class="w3-bar-item w3-button w3-padding-large">{{request.user.first_name}}عزیر
        به صفحه ی خاطرات خوش آمدی </b>
    <a href="{% url 'memories:home' %}" class="w3-bar-item w3-button w3-padding-large">همه خاطرات</a>
    <a href="{% url 'memories:new_memory'%}" class="w3-bar-item w3-button w3-padding-large">ثبت خاطره ی جدید</a>
    <a href="{% url 'memories:edit_profile'%}" class="w3-bar-item w3-button w3-padding-large">ویرایش پروفایل</a>
    <a href="{% url 'users:logout' %}"
       class="w3-bar-item w3-button w3-padding-large" title="My Account">خروج</a>
</div>
{% else %}
<a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
<a href="{% url 'users:login' %}" class="w3-bar-item w3-button w3-padding-large">ورود</a>
<a href="{% url 'users:register' %}" class="w3-bar-item w3-button w3-padding-large">ثبت نام</a>
<a href="{% url 'memories:home' %}" class="w3-bar-item w3-button w3-padding-large">همه خاطرات</a>
{% endif %}

memories/templates/notebook/index.html
{% extends 'notebook/base.html' %}
{% block content %}

{% for memory in memories %}
<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
    <img src="/media/{{memory.writer.profile.avatar}}" alt="Avatar" class="w3-right w3-circle w3-margin-left"
         style="width:60px">
    <h4>{{memory.writer}}</h4><br>
    <hr class="w3-clear">
    <p>{{memory.text}}</p>
    <hr class="w3-clear">
    <div class="w3-row-padding" style="margin:0 -16px">
        <div class="w3-half">
            <img src="/media/{{memory.image}}" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
        </div>
    </div>
    <hr class="w3-clear">
    <a href="{% url 'memories:memory' memory.id %}"
       class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  دیدن این خاطره
    </a>
    {% if request.user.is_authenticated and request.user == memory.writer %}
    <a href="{% url 'memories:edit_memory' memory.id %}"
       class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  ویرایش کردن این خاطره
    </a>
    {% endif %}
    {{memory.history}}
</div>
{% empty %}
<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
    <p>هنوز خاطره ای ثبت نشده !</p>
</div>
<a href="{% url 'memories:new_memory' %}"
   class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  ثبت خاطره ای جدید
    ها
</a>
{% endfor %}
<!-- End Middle Column -->

<br>
{% endblock %}

memories/templates/notebook/lefter.html
{% load static %}
<!-- Left Column -->
<div class="w3-col m3">
    <!-- Profile -->
    {% if request.user.is_authenticated %}
    <div class="w3-card w3-round w3-white">
        <div class="w3-container">
            <h4 class="w3-center">پروفایل من</h4>
            <p class="w3-center"><img src="/media/{{profile1.avatar}}" class="w3-circle"
                                      style="height:106px;width:106px"></p>
            <hr>
            <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> {{profile1.job}}</p>
            <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{profile1.place}}</p>
            <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> {{profile1.birthday}}</p>
            <a href="{% url 'memories:edit_profile'%}"
               class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  ویرایش پروفایل
            </a>
        </div>
    </div>
    <br>
    {% endif %}


    <!-- Accordion -->
    {% if request.user.is_authenticated %}
    <div class="w3-card w3-round">
        <div class="w3-white">
            <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i
                    class="fa fa-users fa-fw w3-margin-right"></i> My Photos
            </button>
            <div id="Demo3" class="w3-hide w3-container">
                <div class="w3-row-padding">
                    <br>
                    <div class="w3-half">
                        {% for ph in memoryph %}
                        <img src="/media/{{ph.image}}" style="width:100%" class="w3-margin-bottom">
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    {% endif %}


    <!-- Interests -->
    <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
            {% if request.user.is_authenticated %}
            <p>علاقه مندی ها</p>
            <p>
                {% for tag in tags %}
                <span class="w3-tag w3-small w3-theme-d5">{{tag.tag}}</span>
                {% endfor %}
                <a href="{% url 'memories:edit_interest' %}"
                   class="w3-button w3-theme-d1 w3-margin-bottom w3-margin-top"><i class="fa fa-pencil"></i>  ویرایش
                    کردن علاقه مندی
                    ها
                </a>
                {% else %}
                {% for memory in memory13 %}
            <div class="w3-card w3-round w3-white w3-center">
                <div class="w3-container">
                    <p>جدید ترین خاطره ها:</p>
                    <img src="/media/{{memory.image}}" alt="Forest" style="width:100%;">
                    <p><strong>{{memory.title}}</strong></p>
                    <p>{{memory.history}}</p>
                    <a href="{% url 'memories:memory' memory.id %}"
                       class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  دیدن این خاطره
                    </a>
                </div>
            </div>
            {% endfor %}
            </p>
            <a href="{% url 'users:login' %}"
               class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  لطفا وارد شوید
            </a>
            {% endif %}

        </div>
    </div>
    <br>
    <!-- End Left Column -->
</div>

memories/templates/notebook/memories.html
{% extends 'notebook/base.html' %}
{% block content %}
{% for memory in memories %}
<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
    <img src="/media/{{memory.writer.profile.avatar}}" alt="Avatar" class="w3-right w3-circle w3-margin-left"
         style="width:60px">
    <h4>{{memory.writer}}</h4><br>
    <hr class="w3-clear">
    <p>{{memory.text}}</p>
    <hr class="w3-clear">
    <div class="w3-row-padding" style="margin:0 -16px">
        <div class="w3-half">
            <img src="/media/{{memory.image}}" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
        </div>
    </div>
    <hr class="w3-clear">
    <a href="{% url 'memories:memory' memory.id %}"
       class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  دیدن این خاطره
    </a>
    <a href="{% url 'memories:edit_memory' memory.id %}"
       class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  ویرایش کردن این خاطره
    </a>
    {{memory.history}}
</div>
{% empty %}
<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
    <p>هنوز خاطره ای ثبت نشده !</p>
</div>
<a href="{% url 'memories:new_memory' %}"
   class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  ثبت خاطره ای جدید
    ها
</a>
{% endfor %}

{% endblock content %}

memories/templates/notebook/memory.html
{% extends 'notebook/base.html' %}
{% block content %}

<h2 style="margin-bottom: 0px">{{memory.title}}</h2><br/>
<h6>{{memory.place}}</h6>
<p class="w3-border w3-padding">{{memory.writer}}: <br/> {{memory.text}}</p>
<h6>هم خاطره هام:</h6>
<p class="w3-border w3-padding">{{memory.ftravel}}</p>
<h6>تاریخ خاطره :</h6>
<p class="w3-border w3-padding">{{memory.history}}</p>
<img src="/media/{{memory.image}}" alt="my history" style="width:100%;border-radius: 10%"
     alt="Northern Lights"
     class="w3-margin-bottom">
<h6>{{memory.create}}</h6>
{% if request.user.is_authenticated and request.user == memory.writer %}
<a href="{% url 'memories:edit_memory' memory.id %}"
   class="w3-button w3-theme"><i class="fa fa-pencil"></i>  ویرایش کردن این خاطره
</a>
{% endif %}
<br/>
{% if request.user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    <h3>نظرات:</h3>
    {{form.as_p}}
    <button type="submit">ثبت نظر</button>
{% endif %}
</form>
{% for comment in comments %}
<p class="w3-border w3-padding">{{comment.writer}}<br/>{{comment.comment}}<br/>
    {% if update %}
    {{comment.update}}
    {% else %}
    {{comment.create}}
    {% endif %}
</p>
{% empty %}
<p class="w3-border w3-padding">هنوز نظری ثبت نشده است !!</p>
{% endfor %}


{% endblock content %}

memories/templates/notebook/new_memory.html
{% extends 'notebook/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if request.user.is_authenticated %}
<form enctype="multipart/form-data" action="{% url 'memories:new_memory' %}" method="post">
    <h2>ثبت یک خاطره جدید</h2>
    {% csrf_token %}
    {{form | crispy}}
    <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  ثبت خاطره</button>
</form>
{% else %}
<h2>دسترسی شما به این صفحه مجاز نیس</h2>
<h6> برای ورود <a href="{% url 'users:login' %}">اینحا</a> کلیک کنید</h6>
<h6> برای ثبت نام <a href="{% url 'users:register' %}">اینحا</a> کلیک کنید</h6>
{% endif %}
{% endblock content %}

memories/templates/notebook/righter.html
{% load static %}
<!-- Right Column -->
<div class="w3-col m2">
    <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
            <p>جدید ترین خاطره:</p>
            <img src="/media/{{lastm.image}}" alt="Forest" style="width:100%;">
            <p><strong>{{lastm.title}}</strong></p>
            <p>{{lastm.history}}</p>
            <a href="{% url 'memories:memory' lastm.id %}"
               class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-pencil"></i>  دیدن این خاطره
            </a>
        </div>
    </div>
    <br>
    <!-- End Right Column -->
</div>